version: '3.8'

services:
  chatgpt-web:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # 如果需要自定义 nginx 配置
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加反向代理
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
      # SSL 证书（如果有的话）
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - chatgpt-web
    restart: unless-stopped
    profiles:
      - proxy
